### PR TITLE
The Best Book

### PR DESCRIPTION
**Pull request by Muhammad0602**
### I have implemented the following: 
- Created a react app and set up the project with linters.
- Chose the `Quran` api.
- Rendered list of items on the homepage
- Showed details about the item on the Details page.
- Added test for the components.
- Styled the project 
- Recorder a video walkthrough
- Deployed the project in render.com

### CODE REVIEW

**Comment by addod19** [comment]
### Hi @Muhammad0602, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because because you did not follow the Git-flow work flow. Thus creating the PR from a feature branch, for example `metrics` branch into the `development` or `dev` branch

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by fobadara — COMMENTED** [review]
Hi @Muhammad0602, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have linters properly set up. You should create a `.github` folder which contains the `.workflows` folder then the linters file

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by fobadara — COMMENTED** [review]
Hi @Muhammad0602, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Your linters are still not set up properly. Your passing linters should reflect in your PR on GitHub. Kindly follow the instructions in this [link](https://github.com/microverseinc/linters-config) for setting it up

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Muhammad0602** [comment]
Hello @fobadara, Sorry but, I did followed the linters configuration and set up everything. Can you please say what is specifically wrong with linters in my project

**Review by 1GORDON — COMMENTED** [review]
##
## Hi @Muhammad0602 ✋

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and it won't affect the number of your weekly reviews.

- [ ] Your project is still using the wrong [GitFlow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md). Kindly ensure your `feature` branch is merging into the `development` branch instead of the `main` branch.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Muhammad0602** [comment]
Hello @1GORDON, This is how I am using GitFlow for all of my projects so far, and all of them were approved. I am really confused, all of my partners do the same. I already created feature branches and PR but merged them because this is a capstone project. I am supposed to create a PR from dev to main for the final PR.  And as I said this is what I and others are doing so far, so can you please clarify what you mean?

**Pull request closed without merging**
